version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    command: ["mongod", "--replSet", "rs0"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    container_name: nextjs-app
    ports:
      - "3000:3000"
      - "5555:5555"
    environment:
      - DATABASE_URL=mongodb://mongo:27017/my_local_db?replicaSet=rs0
      - NODE_ENV=development
    depends_on:
      - mongo
    volumes:
      - ./:/app:cached
      - next_data:/app/.next

volumes:
  mongo_data:
  next_data:
  node_data:
