import type { Metadata } from "next";
import Providers from './providers';
import AuthButtons from './components/AuthButtons';

export const metadata: Metadata = {
  title: "mongodb & prisma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
      <Providers>
      <header>
          <AuthButtons />
        </header>
          {children}
      </Providers>
      </body>
    </html>
  );
}
